Repository deltachat/deltachat-android, pull requests merged in 2023-10, with the labels that each got.

#2692 sanitize filename before creating it in the blobs dir
  src/org/thoughtcrime/securesms/connect/DcHelper.java
  src/org/thoughtcrime/securesms/util/FileUtils.java
Labels: bug

#2699 resume settings activity on language changes
  src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java
Labels: bug

#2703 use only one `audioFocusChangeListener`
  src/org/thoughtcrime/securesms/components/AudioView.java
Labels: bug

#2702 improve screen reader support in conversations
  res/layout/conversation_item_footer.xml
  res/layout/conversation_item_received.xml
  res/layout/conversation_item_received_sticker.xml
  res/layout/conversation_item_sent.xml
  res/layout/conversation_item_sent_sticker.xml
  res/layout/recent_photo_view_item.xml
  src/org/thoughtcrime/securesms/BaseConversationItem.java
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/components/AudioView.java
  src/org/thoughtcrime/securesms/components/ConversationItemFooter.java
  src/org/thoughtcrime/securesms/components/ConversationItemThumbnail.java
  src/org/thoughtcrime/securesms/components/DeliveryStatusView.java
  src/org/thoughtcrime/securesms/components/DocumentView.java
  src/org/thoughtcrime/securesms/components/ThumbnailView.java
  src/org/thoughtcrime/securesms/components/WebxdcView.java
  src/org/thoughtcrime/securesms/util/Util.java
Labels: enhancement

#2705 fix displaying of sticker's footer
  res/layout/conversation_item_received.xml
  res/layout/conversation_item_sent.xml
  res/layout/conversation_item_sent_sticker.xml
  res/layout/conversation_item_sticker.xml
  res/layout/sticker_view.xml
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/components/BorderlessImageView.java
Labels: bug

#2708 allow to resend attachments from chat profile
  res/menu/profile_context.xml
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/MessageSelectorFragment.java
  src/org/thoughtcrime/securesms/ProfileDocumentsFragment.java
  src/org/thoughtcrime/securesms/ProfileGalleryFragment.java
  src/org/thoughtcrime/securesms/ProfileSettingsFragment.java
Labels: enhancement

#2710 use DynamicNoActionBarTheme in ScribbleActivity
  src/org/thoughtcrime/securesms/scribbles/ScribbleActivity.java
Labels: bug

#2712 switch account if needed when opening webxdc app from home shortcut
  src/org/thoughtcrime/securesms/WebxdcActivity.java
Labels: enhancement

#2715 save map preferences per account, not only per chat id
  src/org/thoughtcrime/securesms/map/MapActivity.java
  src/org/thoughtcrime/securesms/map/MapDataManager.java
  src/org/thoughtcrime/securesms/util/Prefs.java
Labels: bug

#2717 allow to set chat background per-account
  src/org/thoughtcrime/securesms/ApplicationContext.java
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/preferences/AppearancePreferenceFragment.java
  src/org/thoughtcrime/securesms/preferences/ChatBackgroundActivity.java
  src/org/thoughtcrime/securesms/util/Prefs.java
Labels: enhancement

#2728 allow to properly click in audio messages in multi-select mode
  res/layout/audio_view.xml
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/ProfileDocumentsAdapter.java
  src/org/thoughtcrime/securesms/components/AudioView.java
Labels: bug

#2731 registration screen: make checkbox use acent color
  res/layout/registration_activity.xml
Labels: bug

#2737 avoid NullPointerException in ConversationListFragment.updateReminders()
  src/org/thoughtcrime/securesms/ConversationListFragment.java
Labels: bug

#2739 tweak action bar theme for dark mode
  res/values-night/colors.xml
  res/values/themes.xml
Labels: enhancement

#2743 remove unnecessary code in ChatBackgroundActivity
  src/org/thoughtcrime/securesms/preferences/ChatBackgroundActivity.java
Labels: bug

#2741 update dcContext in ConversationListAdapter.changeData()
  src/org/thoughtcrime/securesms/ConversationListAdapter.java
  src/org/thoughtcrime/securesms/search/SearchListAdapter.java
Labels: bug

#2744 move reaction pills together with swiped message bubble
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/ConversationSwipeAnimationHelper.java
Labels: bug

#2653 Ask for the name when creating a broadcast list
  res/values/strings.xml
  src/org/thoughtcrime/securesms/GroupCreateActivity.java
Labels: pr waiting for core

#2680 sending reactions
  res/layout/conversation_fragment.xml
  res/values/colors.xml
  res/values/text_styles.xml
  res/xml/preferences_advanced.xml
  src/com/b44t/messenger/rpc/Rpc.java
  src/org/thoughtcrime/securesms/ConversationAdapter.java
  src/org/thoughtcrime/securesms/ConversationFragment.java
  src/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
  src/org/thoughtcrime/securesms/reactions/AddReactionView.java
Labels: enhancement, pr waiting for merge window

#2753 Merge "improve mailto Intent handling in ShareActivity" into main
  androidTest/com/b44t/messenger/uitests/offline/SharingTest.java
  src/org/thoughtcrime/securesms/NewConversationActivity.java
  src/org/thoughtcrime/securesms/ShareActivity.java
  src/org/thoughtcrime/securesms/util/MailtoUtil.java
Labels: bug

#2766 fix avatar letter misplacement
  src/org/thoughtcrime/securesms/qr/QrShowFragment.java
Labels: bug

#2765 allow to deactivate QR codes
  res/menu/qr_show.xml
  src/org/thoughtcrime/securesms/qr/QrActivity.java
  src/org/thoughtcrime/securesms/qr/QrShowActivity.java
  src/org/thoughtcrime/securesms/qr/QrShowFragment.java
Labels: enhancement

#2770 show verifier name+address
  src/org/thoughtcrime/securesms/ProfileSettingsAdapter.java
Labels: enhancement

#2768 'verified chats' are no longer experimental
  res/values/strings.xml
Labels: bug

#2778 remove QR button in group creation screen
  res/layout/group_create_activity.xml
  src/org/thoughtcrime/securesms/GroupCreateActivity.java
Labels: enhancement, verified-chats

#2787 fix bug in group creation activity
  src/org/thoughtcrime/securesms/GroupCreateActivity.java
Labels: bug
