Repository deltachat/deltachat-android, pull requests merged in 2023-11, with the labels that each got.

#2795 properly abort imex process if there is some failure
  src/org/thoughtcrime/securesms/preferences/ListSummaryPreferenceFragment.java
Labels: bug

#2796 improve create group screen (part 2)
  res/layout/group_create_activity.xml
  res/layout/selected_contact_list_item.xml
Labels: enhancement

#2806 fix bugs in GroupCreateActivity
  src/org/thoughtcrime/securesms/GroupCreateActivity.java
Labels: bug

#2805 don't display "new contact" in verified group contact selection
  src/org/thoughtcrime/securesms/ContactSelectionListFragment.java
Labels: bug, verified-chats

#2807 add new-contact activity
  AndroidManifest.xml
  res/layout/new_contact_activity.xml
  res/menu/new_contact.xml
  src/org/thoughtcrime/securesms/BlockedContactsActivity.java
  src/org/thoughtcrime/securesms/ContactSelectionListFragment.java
  src/org/thoughtcrime/securesms/NewConversationActivity.java
  src/org/thoughtcrime/securesms/connect/DcContactsLoader.java
  src/org/thoughtcrime/securesms/contacts/ContactSelectionListAdapter.java
  src/org/thoughtcrime/securesms/contacts/NewContactActivity.java
Labels: enhancement

#2833 use QR icon for QR-invite/join button
  res/drawable-xhdpi/ic_ab_qr.png
  res/drawable/baseline_qr_code_24.xml
  res/menu/text_secure_normal.xml
  src/org/thoughtcrime/securesms/components/AvatarView.java
  src/org/thoughtcrime/securesms/contacts/ContactSelectionListItem.java
Labels: enhancement

#2832 suggestion for better cannot-decrypt message
  res/values/strings.xml
Labels: verified-chats

#2835 hide toolbar onStop and show it again onResume to avoid bug with keyboard
  src/org/thoughtcrime/securesms/ConversationActivity.java
Labels: bug

#2841 improve NewContactActivity, add "scan QR button"
  res/drawable/divider_end.xml
  res/drawable/divider_start.xml
  res/layout/new_contact_activity.xml
  res/values/strings.xml
  res/values/styles.xml
  src/org/thoughtcrime/securesms/contacts/NewContactActivity.java
Labels: enhancement

#2843 Add stock string 173 (Member added)
  res/values/strings.xml
  src/org/thoughtcrime/securesms/connect/DcHelper.java
Labels: core

#2864 check for DC_DOWNLOAD_UNDECIPHERABLE download state
  src/com/b44t/messenger/DcMsg.java
  src/org/thoughtcrime/securesms/ConversationItem.java
Labels: bug

#2873 fix contact creation
  src/org/thoughtcrime/securesms/NewConversationActivity.java
Labels: bug
