Repository deltachat/deltachat-android, pull requests merged in 2024-12, with the labels that each got.

#3457 fix WebxdcActivity.callJavaScriptFunction()
  src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
Labels: bug, blocker

#3465 always prefix href with baseURL
  src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
  src/main/res/raw/webxdc_wrapper.html
Labels: bug

#3473 fix starting of webxdc
  src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
Labels: bug

#3456 notify webxdc events, replies and reactions to own messages even if chat is muted
  src/main/java/com/b44t/messenger/DcContext.java
  src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java
  src/main/java/org/thoughtcrime/securesms/preferences/NotificationsPreferenceFragment.java
  src/main/res/values/strings.xml
  src/main/res/xml/preferences_notifications.xml
Labels: notify

#3463 add webxdc picker
  src/main/AndroidManifest.xml
  src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
  src/main/java/org/thoughtcrime/securesms/WebxdcStoreActivity.java
  src/main/java/org/thoughtcrime/securesms/components/AttachmentTypeSelector.java
  src/main/java/org/thoughtcrime/securesms/mms/AttachmentManager.java
  src/main/java/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
  src/main/java/org/thoughtcrime/securesms/util/Prefs.java
  src/main/res/drawable/baseline_apps_24.xml
  src/main/res/layout/attachment_type_selector.xml
  src/main/res/values/core_colors.xml
  src/main/res/values/strings.xml
  src/main/res/xml/preferences_advanced.xml
Labels: enhancement

#3485 add missing webxdc api
  src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
  src/main/res/raw/webxdc.js
Labels: bug, blocker

#3484 download .xdc files in background
  src/main/java/org/thoughtcrime/securesms/WebxdcStoreActivity.java
Labels: bug

#3497 avoid NPE in ConversationListActivity.onNewIntent()
  src/main/java/org/thoughtcrime/securesms/ConversationListActivity.java
Labels: bug

#3499 avoid IllegalArgumentException dismissing dialog
  src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
Labels: bug

#3507 remove email-address unconditionally from title
  src/main/java/org/thoughtcrime/securesms/ConversationTitleView.java
Labels: enhancement
