Repository deltachat/deltachat-android, pull requests merged in 2024-10, with the labels that each got.

#3348 fix the warning when attaching multiple files
  src/main/java/org/thoughtcrime/securesms/BaseConversationListFragment.java
  src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
  src/main/java/org/thoughtcrime/securesms/util/SendRelayedMessageUtil.java
  src/main/res/values/strings.xml
Labels: bug

#3362 auto-focus group name field
  src/main/res/layout/group_create_activity.xml
Labels: enhancement

#3363 Do not remember "New Contact" screen's tab state
  src/main/java/org/thoughtcrime/securesms/qr/QrActivity.java
Labels: enhancement

#3372 allow to paste from clipboard in RegistrationQrActivity
  src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
  src/main/java/org/thoughtcrime/securesms/WelcomeActivity.java
  src/main/java/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java
  src/main/res/menu/registration_qr_activity.xml
Labels: enhancement

#3374 Allow to share proxy via QR
  jni/dc_wrapper.c
  src/main/java/com/b44t/messenger/DcContext.java
  src/main/java/org/thoughtcrime/securesms/proxy/ProxySettingsActivity.java
  src/main/res/layout/dialog_share_proxy.xml
  src/main/res/values/strings.xml
Labels: enhancement

#3373 allow to set tags on profiles
  src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListFragment.java
  src/main/java/org/thoughtcrime/securesms/accounts/AccountSelectionListItem.java
  src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
  src/main/res/layout/account_selection_list_item.xml
  src/main/res/menu/account_item_context.xml
  src/main/res/values/strings.xml
Labels: enhancement

#3391 improve logging: always log events for accId=0
  src/main/java/org/thoughtcrime/securesms/connect/DcEventCenter.java
Labels: bug, enhancement

#3398 change realtime preference position
  src/main/res/values/strings.xml
  src/main/res/xml/preferences_advanced.xml
Labels: enhancement
