Repository deltachat/deltachat-android, pull requests merged in 2024-01, with the labels that each got.

#2838 upgrade some dependencies
  .github/workflows/preview-apk.yml
  build.gradle
  gradle.properties
Labels: build

#2930 move 'pinned' indicator right for cleaner UI
  src/org/thoughtcrime/securesms/ConversationListItem.java
Labels: enhancement

#2933 hide AddReactionView when user clicks on the attachments buttons
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationFragment.java
Labels: bug

#2942 add global unread messages badge counter
  res/layout/conversation_list_activity.xml
  src/org/thoughtcrime/securesms/ConversationListActivity.java
  src/org/thoughtcrime/securesms/ConversationListFragment.java
  src/org/thoughtcrime/securesms/connect/DcEventCenter.java
Labels: enhancement

#2948 allow to mute/unmute from chatlist
  res/menu/conversation_list.xml
  src/org/thoughtcrime/securesms/ConversationListFragment.java
Labels: enhancement

#2943 copy invite links to clipboard
  res/menu/qr_scan.xml
  src/org/thoughtcrime/securesms/ConversationListActivity.java
  src/org/thoughtcrime/securesms/qr/QrActivity.java
  src/org/thoughtcrime/securesms/qr/QrShowActivity.java
  src/org/thoughtcrime/securesms/qr/QrShowFragment.java
  src/org/thoughtcrime/securesms/util/Util.java
Labels: enhancement
