Repository deltachat/deltachat-android, pull requests merged in 2024-05, with the labels that each got.

#3028 use app:drawableStartCompat instead of android:drawableStart
  res/layout/new_contact_activity.xml
  res/layout/recording_layout.xml
Labels: bug

#3036 clear quote if current draft has no quote
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/components/InputPanel.java
Labels: bug

#3035 disable APNG decoder
  src/org/thoughtcrime/securesms/mms/SignalGlideModule.java
Labels: bug

#3051 allow to show password on "account & password" editing
  src/org/thoughtcrime/securesms/RegistrationActivity.java
Labels: enhancement

#3052 allow to share log instead of copying to clipboard
  AndroidManifest.xml
  res/menu/view_log.xml
  src/org/thoughtcrime/securesms/LogViewActivity.java
  src/org/thoughtcrime/securesms/LogViewFragment.java
Labels: enhancement

#3043 display vcard view type and allow to import/export contacts as vcard
  res/layout/conversation_activity_attachment_editor_stub.xml
  res/layout/conversation_item_received.xml
  res/layout/conversation_item_sent.xml
  res/layout/conversation_item_vcard.xml
  res/layout/vcard_view.xml
  src/com/b44t/messenger/DcMsg.java
  src/com/b44t/messenger/rpc/Rpc.java
  src/com/b44t/messenger/rpc/VcardContact.java
  src/org/thoughtcrime/securesms/AttachContactActivity.java
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationItem.java
  src/org/thoughtcrime/securesms/attachments/Attachment.java
  src/org/thoughtcrime/securesms/attachments/DcAttachment.java
  src/org/thoughtcrime/securesms/components/QuoteView.java
  src/org/thoughtcrime/securesms/components/VcardView.java
  src/org/thoughtcrime/securesms/connect/DcHelper.java
  src/org/thoughtcrime/securesms/contacts/avatars/GeneratedContactPhoto.java
  src/org/thoughtcrime/securesms/contacts/avatars/VcardContactPhoto.java
  src/org/thoughtcrime/securesms/mms/AttachmentManager.java
  src/org/thoughtcrime/securesms/mms/Slide.java
  src/org/thoughtcrime/securesms/mms/VcardSlide.java
  src/org/thoughtcrime/securesms/recipients/Recipient.java
  src/org/thoughtcrime/securesms/util/MediaUtil.java
Labels: enhancement

#3078 bugfix: parse results of scanning QR code in NewConversationActivity
  src/org/thoughtcrime/securesms/NewConversationActivity.java
Labels: bug

#3085 update screenshots
  metadata/en-US/images/phoneScreenshots/1.png
  metadata/en-US/images/phoneScreenshots/2.png
  metadata/en-US/images/phoneScreenshots/3.png
  metadata/en-US/images/phoneScreenshots/4.png
  metadata/en-US/images/phoneScreenshots/5.png
  metadata/en-US/images/phoneScreenshots/6.png
  metadata/en-US/images/phoneScreenshots/7.png
  metadata/en-US/images/phoneScreenshots/8.png
  store/screenshot-01.png
  store/screenshot-02.png
  store/screenshot-03.png
  store/screenshot-04.png
  store/screenshot-05.png
  store/screenshot-06.png
  store/screenshot-07.png
  store/screenshot-08.png
  store/screenshots.txt
Labels: app-store

#3087 improve logs: use emojis to mark the log level for easier visibility
  src/org/thoughtcrime/securesms/LogViewFragment.java
Labels: enhancement

#3092 check if push is sufficient before adding device message
  src/org/thoughtcrime/securesms/components/reminder/DozeReminder.java
Labels: bug
