Repository deltachat/deltachat-android, pull requests merged in 2024-11, with the labels that each got.

#3410 fix: Accept the deprecated 3 as an alias for 2
  src/main/java/org/thoughtcrime/securesms/RegistrationActivity.java
  src/main/res/layout/registration_activity.xml
  src/main/res/values/arrays.xml
Labels: bug

#3400 improve msg_action_button
  src/main/java/org/thoughtcrime/securesms/ConversationItem.java
  src/main/res/layout/conversation_item_received.xml
  src/main/res/layout/conversation_item_sent.xml
  src/main/res/values/dimens.xml
Labels: enhancement

#3422 change proxy protocol label position
  src/main/res/layout/proxy_list_item.xml
Labels: enhancement

#3424 remove internal font scaling preference
  src/main/java/org/thoughtcrime/securesms/ConversationItem.java
  src/main/java/org/thoughtcrime/securesms/components/emoji/AutoScaledEmojiTextView.java
  src/main/java/org/thoughtcrime/securesms/preferences/AppearancePreferenceFragment.java
  src/main/java/org/thoughtcrime/securesms/util/Prefs.java
  src/main/java/org/thoughtcrime/securesms/util/ViewUtil.java
  src/main/res/values/arrays.xml
  src/main/res/values/strings.xml
  src/main/res/xml-v29/preferences_appearance.xml
  src/main/res/xml/preferences_appearance.xml
Labels: bug

#3434 fix: Don't change display name when starting to create a new account and going back
  src/main/java/org/thoughtcrime/securesms/InstantOnboardingActivity.java
Labels: bug

#3377 notify reactions added
  src/main/java/com/b44t/messenger/DcContext.java
  src/main/java/org/thoughtcrime/securesms/connect/DcEventCenter.java
  src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java
Labels: notify, enhancement

#3438 allow to open deep-link to webxdc
  jni/dc_wrapper.c
  src/main/java/com/b44t/messenger/DcMsg.java
  src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
  src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
  src/main/res/raw/webxdc_wrapper.html
Labels: enhancement, webxdc, wait-for-core

#3443 notify DC_EVENT_INCOMING_WEBXDC_NOTIFY
  src/main/java/com/b44t/messenger/DcContext.java
  src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
  src/main/java/org/thoughtcrime/securesms/connect/DcEventCenter.java
  src/main/java/org/thoughtcrime/securesms/notifications/NotificationCenter.java
Labels: webxdc

#3446 remove 'description' parameter from webxdc's sendUpdate()
  jni/dc_wrapper.c
  src/main/java/com/b44t/messenger/DcContext.java
  src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
  src/main/res/raw/webxdc.js
Labels: webxdc

#3447 add "show in chat" to webxdc menu
  src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
  src/main/res/menu/webxdc.xml
Labels: webxdc

#3452 reply/mark-read actions refer to chat, not to message
  src/main/java/org/thoughtcrime/securesms/notifications/RemoteReplyReceiver.java
Labels: webxdc
