Repository deltachat/deltachat-android, pull requests merged in 2024-04, with the labels that each got.

#2985 add strings needed by core to show reactions in summaries
  res/values/strings.xml
  src/org/thoughtcrime/securesms/connect/DcHelper.java
Labels: PR waiting for core

#2997 allow to open troubleshooting menu option directly from offline help
  src/org/thoughtcrime/securesms/LocalHelpActivity.java
  src/org/thoughtcrime/securesms/PassphraseRequiredActionBarActivity.java
  src/org/thoughtcrime/securesms/qr/BackupTransferActivity.java
  src/org/thoughtcrime/securesms/qr/RegistrationQrActivity.java
Labels: enhancement

#3006 fix bug in WebxdcActivity: don't try to get iframe in "allow internet" mode
  src/org/thoughtcrime/securesms/FullMsgActivity.java
  src/org/thoughtcrime/securesms/WebViewActivity.java
  src/org/thoughtcrime/securesms/WebxdcActivity.java
Labels: bug

#3005 use new experimental maps integration
  assets/webxdc/maps.xdc
  build.gradle
  jni/dc_wrapper.c
  src/com/b44t/messenger/DcContext.java
  src/org/thoughtcrime/securesms/ConversationActivity.java
  src/org/thoughtcrime/securesms/ConversationListActivity.java
  src/org/thoughtcrime/securesms/WebxdcActivity.java
  src/org/thoughtcrime/securesms/map/AddPoiView.java
  src/org/thoughtcrime/securesms/map/DCMapFragment.java
  src/org/thoughtcrime/securesms/map/DataCollectionTask.java
  src/org/thoughtcrime/securesms/map/DataCollector.java
  src/org/thoughtcrime/securesms/map/GenerateInfoWindowTask.java
  src/org/thoughtcrime/securesms/map/MapActivity.java
  src/org/thoughtcrime/securesms/map/MapDataManager.java
  src/org/thoughtcrime/securesms/map/MarkerView.java
  src/org/thoughtcrime/securesms/map/MarkerViewManager.java
  src/org/thoughtcrime/securesms/map/SendingTask.java
  src/org/thoughtcrime/securesms/map/model/FilterProvider.java
  src/org/thoughtcrime/securesms/map/model/MapSource.java
  src/org/thoughtcrime/securesms/util/Prefs.java
Labels: enhancement

#3002 allow to pin, archive, etc. when searching in the chatlist
  res/layout/fragment_search.xml
  res/menu/conversation_list.xml
  res/menu/conversation_list_batch_archive.xml
  res/menu/conversation_list_batch_pin.xml
  res/menu/conversation_list_batch_unarchive.xml
  src/org/thoughtcrime/securesms/BaseConversationListAdapter.java
  src/org/thoughtcrime/securesms/BaseConversationListFragment.java
  src/org/thoughtcrime/securesms/ConversationListAdapter.java
  src/org/thoughtcrime/securesms/ConversationListFragment.java
  src/org/thoughtcrime/securesms/search/SearchFragment.java
  src/org/thoughtcrime/securesms/search/SearchListAdapter.java
  src/org/thoughtcrime/securesms/search/SearchViewModel.java
Labels: bug, enhancement

#3008 fix openOnlineUrl(), mailto/openpgp4fpr has to open externally
  src/org/thoughtcrime/securesms/WebViewActivity.java
  src/org/thoughtcrime/securesms/WebxdcActivity.java
Labels: bug

#3011 remove unused relicts from Mapbox -> Leaflet move
  jni/dc_wrapper.c
  res/values/attrs.xml
  src/com/b44t/messenger/DcArray.java
  src/com/b44t/messenger/DcContext.java
  src/org/thoughtcrime/securesms/components/rangeslider/RangeSliderView.java
  src/org/thoughtcrime/securesms/components/rangeslider/TextLayer.java
  src/org/thoughtcrime/securesms/components/rangeslider/ThumbLayer.java
  src/org/thoughtcrime/securesms/components/rangeslider/TimeRangeSlider.java
  src/org/thoughtcrime/securesms/components/rangeslider/TrackLayer.java
Labels: location

#3001 add strings needed for instant onboarding
  res/values/strings.xml
Labels: enhancement
