Repository deltachat/deltachat-android, pull requests merged in 2025-02, with the labels that each got.

#3585 fix: Opening files in external apps always works now
  src/androidTest/java/com/b44t/messenger/uitests/offline/SharingTest.java
  src/main/java/org/thoughtcrime/securesms/connect/AttachmentsContentProvider.java
  src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
Labels: bug

#3586 improve improved saved messages
  src/main/java/com/b44t/messenger/DcMsg.java
  src/main/java/org/thoughtcrime/securesms/BindableConversationItem.java
  src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
  src/main/java/org/thoughtcrime/securesms/ConversationItem.java
  src/main/java/org/thoughtcrime/securesms/components/ConversationItemFooter.java
  src/main/java/org/thoughtcrime/securesms/util/SendRelayedMessageUtil.java
  src/main/java/org/thoughtcrime/securesms/util/views/ConversationAdaptiveActionsToolbar.java
  src/main/res/drawable-night/jumpto_btn_bg.xml
  src/main/res/drawable/baseline_bookmark_24.xml
  src/main/res/drawable/baseline_star_outline_24.xml
  src/main/res/drawable/jumpto_btn_bg.xml
  src/main/res/drawable/rounded_arrow_forward_24.xml
  src/main/res/layout/conversation_item_footer.xml
  src/main/res/layout/conversation_item_received.xml
  src/main/res/layout/conversation_item_sent.xml
  src/main/res/menu/conversation_context.xml
Labels: enhancement

#3073 improve saved messages
  jni/dc_wrapper.c
  src/main/java/com/b44t/messenger/DcContext.java
  src/main/java/com/b44t/messenger/DcMsg.java
  src/main/java/org/thoughtcrime/securesms/BindableConversationItem.java
  src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
  src/main/java/org/thoughtcrime/securesms/ConversationItem.java
  src/main/java/org/thoughtcrime/securesms/components/ConversationItemFooter.java
  src/main/java/org/thoughtcrime/securesms/util/SendRelayedMessageUtil.java
  src/main/res/drawable-night/jumpto_btn_bg.xml
  src/main/res/drawable/baseline_bookmark_24.xml
  src/main/res/drawable/jumpto_btn_bg.xml
  src/main/res/drawable/rounded_arrow_forward_24.xml
  src/main/res/layout/conversation_item_footer.xml
  src/main/res/layout/conversation_item_received.xml
  src/main/res/layout/conversation_item_sent.xml
Labels: enhancement

#3588 fix: hide 'clone chat' if there is no chat
  src/main/java/org/thoughtcrime/securesms/ProfileActivity.java
Labels: bug

#3595 allow to add any chat to the home screen
  src/main/java/org/thoughtcrime/securesms/BaseConversationListFragment.java
  src/main/java/org/thoughtcrime/securesms/connect/DirectShareUtil.java
  src/main/res/menu/conversation_list.xml
Labels: enhancement

#3603 update forward icon
  src/main/res/drawable-hdpi/ic_forward_white_24dp.png
  src/main/res/drawable-mdpi/ic_forward_white_24dp.png
  src/main/res/drawable-xhdpi/ic_forward_white_24dp.png
  src/main/res/drawable-xxhdpi/ic_forward_white_24dp.png
  src/main/res/drawable/ic_forward_white_24dp.xml
Labels: enhancement

#3610 remove some android4 depenedencies
  build.gradle
Labels: android4

#3614 update gson lib that was pinned for android4 compat
  build.gradle
Labels: android4

#3601 allow to edit message
  jni/dc_wrapper.c
  src/main/java/com/b44t/messenger/DcContext.java
  src/main/java/com/b44t/messenger/DcMsg.java
  src/main/java/org/thoughtcrime/securesms/ConversationActivity.java
  src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
  src/main/java/org/thoughtcrime/securesms/ConversationItem.java
  src/main/java/org/thoughtcrime/securesms/components/ConversationItemFooter.java
  src/main/java/org/thoughtcrime/securesms/components/InputPanel.java
  src/main/java/org/thoughtcrime/securesms/components/QuoteView.java
  src/main/java/org/thoughtcrime/securesms/util/views/ConversationAdaptiveActionsToolbar.java
  src/main/res/layout/conversation_item_footer.xml
  src/main/res/menu/conversation.xml
  src/main/res/menu/conversation_context.xml
Labels: wait-for-core
