Repository deltachat/deltachat-android, pull requests merged in 2025-03, with the labels that each got.

#3642 clarify chat deletion impact
  src/main/res/values/strings.xml
Labels: wait-for-core

#3665 call rpc.start() before it is used
  src/main/java/com/b44t/messenger/rpc/Rpc.java
  src/main/java/org/thoughtcrime/securesms/ApplicationContext.java
Labels: bug

#3656 remove notifications from chat that was deleted from other device
  src/main/java/com/b44t/messenger/DcContext.java
  src/main/java/org/thoughtcrime/securesms/ConversationListFragment.java
Labels: wait-for-core

#3633 allow to edit and delete for all
  CHANGELOG.md
  jni/dc_wrapper.c
  src/main/java/com/b44t/messenger/DcContext.java
  src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
  src/main/java/org/thoughtcrime/securesms/MediaPreviewActivity.java
  src/main/java/org/thoughtcrime/securesms/MessageSelectorFragment.java
Labels: enhancement

#3594 hide some option in Encryption category
  CHANGELOG.md
  src/main/java/com/b44t/messenger/DcMsg.java
  src/main/java/org/thoughtcrime/securesms/ConversationAdapter.java
  src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
  src/main/java/org/thoughtcrime/securesms/ConversationItem.java
  src/main/java/org/thoughtcrime/securesms/connect/DcHelper.java
  src/main/java/org/thoughtcrime/securesms/preferences/AdvancedPreferenceFragment.java
  src/main/res/values/strings.xml
  src/main/res/xml/preferences_advanced.xml
Labels: enhancement

#3687 avoid crash when clicking orphan info messages from webxdc
  CHANGELOG.md
  src/main/java/org/thoughtcrime/securesms/ConversationFragment.java
  src/main/java/org/thoughtcrime/securesms/WebxdcActivity.java
Labels: bug
